# Generated by Django 6.0.3 on 2026-04-25 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0002_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='extra_links',
            field=models.JSONField(blank=True, default=list, verbose_name='Дополнительные ссылки'),
        ),
    ]
