# Generated by Django 6.0.3 on 2026-04-26 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0004_subjectimage_difficulty_task_resource'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='status',
        ),
        migrations.AddField(
            model_name='task',
            name='progress_status',
            field=models.CharField(choices=[('not_started', 'Не начато'), ('in_progress', 'В процессе'), ('completed', 'Выполнено')], default='not_started', max_length=20, verbose_name='Статус выполнения'),
        ),
    ]
