# Generated by Django 6.0.3 on 2026-04-28 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0006_task_completed_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subjectimage',
            name='difficulty',
        ),
        migrations.AddField(
            model_name='profile',
            name='email_notifications_enabled',
            field=models.BooleanField(default=True, verbose_name='Уведомления по почте'),
        ),
        migrations.AddField(
            model_name='subject',
            name='difficulty',
            field=models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=3, verbose_name='Сложность (1-5)'),
        ),
    ]
