# Generated by Django 6.0.3 on 2026-05-05 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0007_remove_subjectimage_difficulty_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='google_drive_link',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='notion_link',
        ),
    ]
