# Generated by Django 5.2.13 on 2026-05-19 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0008_remove_subject_google_drive_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar_url',
            field=models.CharField(default='avatar1.png', max_length=255),
        ),
    ]
